Layout/EndOfLine:
  EnforcedStyle: lf
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/AbcSize:
  Enabled: true
  Max: 22
Metrics/ClassLength:
  Enabled: true
  Max: 1000
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7
Metrics/MethodLength:
  Enabled: true
  Max: 65
Style/ExponentialNotation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
